### ISSUE TITLE
Optional Parameters

### ISSUE THREAD

**Issue by gracedigital** [patricksavalle/slim-request-params#2]
I wanted to be able to use this middleware to verify parameters. Some of the parameters are optional.  If they are passed in they need to be validated but if they are not present they they should just be give null or empty string.

In the readme it says that "Missing parameters are set to the given default or null if no default is given.". 

If I define the following route
        $app->get('', 'API\Controllers\StationController:findAll')->add(
            new QueryParameters([
                "{name:\w+},",
                "{genre:\w+},",
                "{state:[a-zA-Z]{2}},%",
                "{country:[a-zA-Z]{2}},%",            
                "{offset:\int},1",
                "{limit:\int},10"
            ])
        );
When I call this route I get an error "Invalid validation pattern: {name:\\w+}"
If I change the validation pattern to "{name:\w+},%" or "{name:\w+},''" I can get it to work.  However my understanding of the readme was that missing parameters would be set to null if they didn't have a value.  
If I define the validation pattern without a default value "{name:\w+}", and do not pass one in with the query then I get an error that the parameter is missing. 

REQUEST = http://127.0.0.1:8888/radio/stations?offset=0
RESPONSE = "Missing parameter: name"

What validation pattern is needed to assign "null" to parameters that are not passed in?

**Comment by patricksavalle** [comment]
I will look into this. Hang on :)

**Comment by patricksavalle** [comment]
It is the comma in the pattern. This should work (removed the comma's in patterns without a default.

    $app->get('', 'API\Controllers\StationController:findAll')->add(
        new QueryParameters([
        "{name:\w+,\optional}",
        "{genre:\w+,\optional}",
        "{state:[a-zA-Z]{2}},%",
        "{country:[a-zA-Z]{2}},%",
        "{offset:\int},1",
        "{limit:\int},10"
        ])
    );

Or of you need null as default:

    $app->get('', 'API\Controllers\StationController:findAll')->add(
        new QueryParameters([
        "{name:\w+,null}",
        "{genre:\w+,null}",
        "{state:[a-zA-Z]{2}},%",
        "{country:[a-zA-Z]{2}},%",
        "{offset:\int},1",
        "{limit:\int},10"
        ])
    );

I will correct the documentation.
