### ISSUE TITLE
Is there a way to get the QueryParams to accept single quote characters in the parameter value?

### ISSUE THREAD

**Issue by gracedigital** [patricksavalle/slim-request-params#3]
RULE:
        $app->get('', 'API\Controllers\MainController:findAll')->add(
            new QueryParameters([
                "{genre:\w+},%",
                "{provider:\w+},%",        
                "{offset:\int},0",
                "{limit:\int},10"
            ])
        );
REQUEST:
http://192.168.86.239:8888/api/entity?genre=00's&provider=ABC&limit=10&offset=0
RESULT:
[**Invalid parameter value for key: genre (00's)**]

I tried several regex patterns but could not get any to allow a single quote in the parameter value.

**Comment by patricksavalle** [comment]
Is that a valid URL?

You can use this pattern ".+"  ('one or more of anything'), like this:

    $app->get('', 'API\Controllers\MainController:findAll')->add(
        new QueryParameters([
            "{genre:.+},%",
            "{provider:\w+},%",
            "{offset:\int},0",
            "{limit:\int},10"
        ])
    );
